#version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-ai-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db-ai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_USERNAME: elzat7@ya.ru
      SPRING_MAIL_PASSWORD: xbjkrwlljffeifdo
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0.41
    container_name: mysql-8.0-ai
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db-ai
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
volumes:
  db_data:
